platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'FireCache_Example' do
  
  pod 'FireCache', :path => '../'

  target 'FireCache_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
    
  end
end
